### ISSUE TITLE
Localisation_Toolkit: Reinventing the wheel

### ISSUE THREAD

**Issue by tg359** [BHoM/Localisation_Toolkit#11]
The complexity of setting up a units conversion method applicable to all BHoM toolkits once again asks the question - "_Why are we redefining the wheel and doing this ourselves when someone else has done this already?!_"

Would it not be more time and cost effective to wrap the excellent [UnitsNet](https://github.com/angularsen/UnitsNet) nuget package which already implements pretty much ALL of the converts we could possible want. We'd maintain control over versioning so that a fixed [UnitsNet](https://github.com/angularsen/UnitsNet) version is used to prevent any weirdness later on. We'd have the testing of all those contributing to the original code as well as our own.

Yes, there may be issues with the source code, but that's why we test. There's also a reason why this hasn't been done already - in that it's pretty complicated once you get past metres and grams. Do we define everything in base SI units, then everything else is derived (e.g. a volumetric unit defined by three length units, or being defined by an area unit multiplied by another length unit)? Do we write conversions between all possible units, or to and from the base unit/s only?

Lots of questions here, but given that there is already a well defined method for unit conversions  with 570k downloads since 2013 there's a lot of legwork done already. It's also under MIT No Attribution license so would fit within the BHoM framework.

**Comment by JosefTaylor** [comment]
This is very interesting to me. It could be used to underpin our entire oM, though I think it would be simpler to just make a wrapper here and force all adapters to convert to SI from whatever the software is using.

**Comment by JosefTaylor** [comment]
also to echo @tg359, writing all possible conversions is of course bonkers, but writing conversions from all possible units to SI is still pretty bonkers.

**Comment by al-fisher** [comment]
Reached agreement previously that a wrapping of UnitsNet https://github.com/angularsen/UnitsNet in a new Units_Engine here within the Localisation_Toolkit is the way forward.
I will close this issue now as resolved - to open new issues for actioning development 
https://github.com/BHoM/Localisation_Toolkit/issues/18
