### ISSUE TITLE
Units_Engine: provide ToUnit( quantity, unit ) and FromUnit( quantity, unit)

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Localisation_Toolkit#51]
#### Description:

Methods ToUnit( double quantity, string unit ) and FromUnit( double quantity, string unit ), which would attempt to find a match for the input unit string, and use the corresponding convert method.

If a user provided "inch", "inches", "inch", we would call ToInch(), if a user provided "square inches", "in^2", "inch^2", etc. we call ToSquareInch(). This would allow convenient usage in spreadsheets where a list of properties and their units are provided, and the quantity is to be extracted and converted from several BHoM objects:
```
    A              B                 C                 D
1                  Height            Width             Area
2                  in                in                in^2
3 Object1          ToUnit(getProperty(A3, B1), B2)
4 Object2
```

**Comment by FraserGreenroyd** [comment]
I have concerns with such a method, doing anything that requires string input and matching can end up getting into a long chain of `if` statements to capture all the possible ways of saying `in^2` for example.

What would b the use case for this? And where are the expected benefits of such a method, as opposed to what we currently have which just requires a user to look up the conversion they want and utilise it?

**Comment by al-fisher** [comment]
I assume @JosefTaylor you are coming at this from an "Excel Template" direction. Where we certainly imagine cells with units clearly written out in them in text form - very useful for documentation and meaning the excel sheet can be printed directly as part of reporting.

I do think the above is therefore worth exploring in some capacity. 

We have talked historically about having a layer in the UI to allow control over how the UI handles converts and rendering/formatting data in non-SI. See good issue here: https://github.com/BHoM/BHoM_UI/issues/128
with proposals about how to the existing GH/Excel UIs differently

@adecler @kayleighhoude worth a slight consideration in your current planning around near and mid future excel capability potentially. 
@IsakNaslundBh @rwemay FYI we have had some good discussions on this possible capability previously.

**Comment by JosefTaylor** [comment]
This is old, but I just came back to it on a little UI rabbit-hole.
I think there are a few ways of dealing with the string matching problem, chiefly using enums and a dictionary - an enum which contains all the units (or maybe one enum per SI base unit, or one per quantity type), and a dictionary<string,enum> containing all the various ways one could think to write these, corresponding to the proper enum.
That way, it's just a 'TryGetValue(input)' and a switch/case statement for the enums.
